# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
  - name: Image
    displayName: 'Testing parameters'
    default: 'macOS-latest'
    type: string
    values:
      - windows-latest
      - ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Testing params'