name: first workflow

on:
  push:
    branches: main

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create abc directory
        run: mkdir -p abc

      - name: Create file inside abc folder
        run: echo "This is a new file created by GitHub Actions." > abc/newfile.txt

      - name: Commit and push changes
        run: echo "Created successfully"
